services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - USER_SERVICE_DATABASE=${USER_SERVICE_DATABASE}
      - USER_SERVICE_USERNAME=${USER_SERVICE_USERNAME}
      - USER_SERVICE_PASSWORD=${USER_SERVICE_PASSWORD}
      - EVENT_SERVICE_DATABASE=${EVENT_SERVICE_DATABASE}
      - EVENT_SERVICE_USERNAME=${EVENT_SERVICE_USERNAME}
      - EVENT_SERVICE_PASSWORD=${EVENT_SERVICE_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
